title: Elena de Sus
author: GitHub User
email: elena@ctxt.es
description: > # this means to ignore newlines until "baseurl:"
  Periodista en CTXT
# social links
twitter_username:  elena_sg # DO NOT include the @ character, or else the build will fail!
github_username:  elenadesus # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
